brand:
  name: CapiConf
menu-string: Menu

nav:
  - title: Palestrantes
    url: '#speakers'
  - title: Agenda
    url: '#agenda'
  - title: Organização
    url: '#organization'

copyright: Copyright &copy; Capivara Conference 2018

social-buttons:
  - icon: fa fa-twitter
    url: '#' 
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Termos de Uso
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Fechar'
